#!/usr/bin/env python3
"""eat. 食材データベース生成スクリプト"""
import json, os

OUT = os.path.join(os.path.dirname(__file__), '..', 'assets', 'databases', 'foods_all.json')

# body_parts: brain, eyes, muscles, bones, immune, sleep, skin, gut
# functional_ingredients ids: imidapeptide, dha, epa, gaba, lactic_acid_bacteria,
#   catechin, lycopene, lutein, astaxanthin, coq10, carnitine, glucosamine,
#   collagen, beta_glucan, quercetin

def food(id, name, reading, en, category, cal, pro, fat, carb, fib,
         va=0, vd=0, ve=0, vk=0, vb1=0, vb2=0, vb6=0, vb12=0, vc=0,
         nia=0, fol=0, pan=0, bio=0,
         ca=0, mg=0, k=0, na=0, ph=0, fe=0, zn=0, cu=0, mn=0,
         io=0, se=0, cr=0, mo=0,
         func=None, effects=None, tips=None, craving=None, cook=None, tags=None,
         ref=False, src="mext_2023"):
    return {
        "id": id, "name": name, "name_reading": reading, "name_en": en,
        "category": category, "data_source": src, "is_reference_value": ref,
        "per_100g": {
            "calories": cal, "protein_g": pro, "fat_g": fat,
            "carbs_g": carb, "fiber_g": fib,
            "vitamins": {"vitamin_a_ug":va,"vitamin_d_ug":vd,"vitamin_e_mg":ve,
                "vitamin_k_ug":vk,"vitamin_b1_mg":vb1,"vitamin_b2_mg":vb2,
                "vitamin_b6_mg":vb6,"vitamin_b12_ug":vb12,"vitamin_c_mg":vc,
                "niacin_mg":nia,"folate_ug":fol,"pantothenic_acid_mg":pan,"biotin_ug":bio},
            "minerals": {"calcium_mg":ca,"magnesium_mg":mg,"potassium_mg":k,
                "sodium_mg":na,"phosphorus_mg":ph,"iron_mg":fe,"zinc_mg":zn,
                "copper_mg":cu,"manganese_mg":mn,"iodine_ug":io,
                "selenium_ug":se,"chromium_ug":cr,"molybdenum_ug":mo}
        },
        "functional_ingredients": func or [],
        "body_parts_effects": effects or {},
        "combination_tips": tips or [],
        "craving_signal": craving or {"has_signal": False, "message": None},
        "cooking_tips": cook or [],
        "tags": tags or []
    }

def fi(id, name, amount, effects_list):
    return {"id":id,"name":name,"amount_per_100g":amount,"amount_note":"参考値","body_effects":effects_list}

def tip(partner, effect, reason):
    return {"partner_food_example":partner,"effect":effect,"reason":reason}

FOODS = [
    # ── 肉類 ──
    food("chicken_breast","鶏むね肉","とりむねにく","Chicken Breast","肉類",
         116,23.3,1.9,0,0, va=3,vd=0.1,ve=0.3,vk=17,vb1=0.1,vb2=0.1,vb6=0.64,vb12=0.3,vc=3,
         nia=11.8,fol=8,pan=2.1,bio=5.5, ca=4,mg=27,k=350,na=42,ph=220,fe=0.3,zn=0.8,se=27,
         func=[fi("imidapeptide","イミダペプチド","約200mg",["脳疲労回復","抗酸化","持久力向上"])],
         effects={"brain":{"score_contribution":0.8,"reason":"イミダペプチドが脳疲労回復をサポート"},
                  "muscles":{"score_contribution":0.9,"reason":"高タンパクで筋肉修復をサポート"},
                  "immune":{"score_contribution":0.4,"reason":"セレンが免疫機能をサポート"}},
         tips=[tip("レモン・パプリカ","抗酸化効果が高まる可能性があります","ビタミンCがイミダペプチドの酸化を防ぐ")],
         cook=["加熱しすぎるとイミダペプチドが減少するため、さっと火を通す程度が最適"],
         tags=["高タンパク","低脂質","脳疲労","アスリート","ダイエット"]),

    food("chicken_thigh","鶏もも肉","とりももにく","Chicken Thigh","肉類",
         204,17.3,14.2,0,0, va=40,vd=0.3,ve=0.5,vk=15,vb1=0.1,vb2=0.15,vb6=0.25,vb12=0.4,
         ca=5,mg=20,k=270,na=75,ph=170,fe=0.6,zn=1.6,se=15,
         func=[fi("imidapeptide","イミダペプチド","約100mg",["疲労回復","抗酸化"])],
         effects={"muscles":{"score_contribution":0.7,"reason":"タンパク質が筋肉修復をサポート"},
                  "brain":{"score_contribution":0.4,"reason":"イミダペプチドが脳疲労をサポート"}},
         tags=["タンパク質","疲労回復"]),

    food("chicken_tenderloin","鶏ささみ","とりささみ","Chicken Tenderloin","肉類",
         98,23.0,0.8,0,0, vb6=0.6,vb12=0.2,nia=10.5,
         ca=3,mg=26,k=390,na=40,ph=210,fe=0.3,zn=0.6,se=20,
         func=[fi("imidapeptide","イミダペプチド","約150mg",["脳疲労回復","持久力向上"])],
         effects={"brain":{"score_contribution":0.7,"reason":"イミダペプチドが脳をサポート"},
                  "muscles":{"score_contribution":0.9,"reason":"最高純度のタンパク質で筋肉をサポート"}},
         tags=["超低脂質","高タンパク","ダイエット","アスリート"]),

    food("chicken_liver","鶏レバー","とりればー","Chicken Liver","肉類",
         111,18.9,3.1,0.6,0, va=14000,vd=0.2,vb1=0.38,vb2=1.8,vb6=0.65,vb12=44,vc=20,
         fol=1300,pan=7.7,bio=232, ca=5,mg=19,k=330,na=85,ph=300,fe=9.0,zn=3.3,cu=0.32,se=55,
         func=[fi("coq10","コエンザイムQ10","約13mg",["エネルギー産生","抗酸化","心臓機能サポート"])],
         effects={"brain":{"score_contribution":0.9,"reason":"鉄・ビタミンB12が脳機能をサポート"},
                  "immune":{"score_contribution":0.9,"reason":"ビタミンAが免疫機能を強力にサポート"},
                  "skin":{"score_contribution":0.7,"reason":"ビタミンAが肌の再生をサポート"},
                  "eyes":{"score_contribution":0.9,"reason":"ビタミンAが目の健康をサポート"}},
         tips=[tip("レモン汁","鉄の吸収率が向上する可能性があります","ビタミンCが非ヘム鉄の吸収を促進"),
               tip("ごま油炒め","ビタミンAの吸収率が高まる可能性があります","脂溶性ビタミンAは油と一緒に摂ると吸収される")],
         tags=["鉄分","ビタミンA","ビタミンB12","貧血","妊婦"]),

    food("pork_loin","豚ロース","ぶたろーす","Pork Loin","肉類",
         248,19.3,19.2,0.2,0, vb1=0.69,vb2=0.22,vb6=0.32,vb12=0.4,nia=5.6,
         ca=3,mg=21,k=310,na=45,ph=180,fe=0.5,zn=2.0,se=18,
         effects={"brain":{"score_contribution":0.6,"reason":"ビタミンB1が脳のエネルギー代謝をサポート"},
                  "muscles":{"score_contribution":0.7,"reason":"タンパク質・亜鉛が筋肉をサポート"}},
         tips=[tip("にんにく","疲労回復効果が高まる可能性があります","アリシンがビタミンB1の吸収を促進")],
         tags=["ビタミンB1","疲労回復"]),

    food("pork_belly","豚バラ","ぶたばら","Pork Belly","肉類",
         395,14.4,35.4,0.1,0, vb1=0.51,vb2=0.13,vb6=0.23,vb12=0.4,
         ca=3,mg=14,k=230,na=50,ph=130,fe=0.5,zn=1.5,
         effects={"brain":{"score_contribution":0.4,"reason":"ビタミンB1が脳エネルギー代謝をサポート"}},
         tags=["高カロリー","ビタミンB1"]),

    food("pork_fillet","豚ヒレ","ぶたひれ","Pork Tenderloin","肉類",
         115,22.2,3.7,0.3,0, vb1=1.32,vb2=0.25,vb6=0.54,vb12=0.5,nia=7.6,
         ca=4,mg=25,k=410,na=46,ph=230,fe=1.0,zn=2.2,se=18,
         effects={"brain":{"score_contribution":0.7,"reason":"ビタミンB1が脳エネルギー代謝を強力にサポート"},
                  "muscles":{"score_contribution":0.8,"reason":"高タンパク・低脂質で筋肉修復をサポート"}},
         tags=["低脂質","高タンパク","ビタミンB1"]),

    food("pork_liver","豚レバー","ぶたればー","Pork Liver","肉類",
         114,20.4,3.4,2.5,0, va=13000,vd=1.3,vb1=0.34,vb2=3.6,vb6=0.61,vb12=25,vc=20,
         fol=810,pan=6.3, ca=7,mg=20,k=290,na=55,ph=340,fe=13.0,zn=6.9,cu=0.47,se=67,
         effects={"brain":{"score_contribution":0.9,"reason":"鉄・B12が脳に不可欠"},
                  "immune":{"score_contribution":0.9,"reason":"ビタミンAが免疫を強力サポート"},
                  "eyes":{"score_contribution":1.0,"reason":"ビタミンAが目の健康を強力サポート"}},
         tags=["最高鉄分","ビタミンA","B12","貧血"]),

    food("beef_loin","牛ロース","ぎゅうろーす","Beef Loin","肉類",
         380,14.3,36.1,0.2,0, vb2=0.16,vb6=0.29,vb12=1.8,nia=4.1,
         ca=4,mg=15,k=230,na=55,ph=140,fe=1.0,zn=3.0,
         func=[fi("carnitine","カルニチン","約70mg",["脂肪燃焼サポート","エネルギー産生"])],
         effects={"muscles":{"score_contribution":0.8,"reason":"タンパク質・亜鉛が筋肉をサポート"},
                  "brain":{"score_contribution":0.5,"reason":"B12が神経機能をサポート"}},
         craving={"has_signal":True,"message":"脂肪をエネルギーに変える力が落ちているサインかもしれません"},
         tags=["亜鉛","カルニチン","筋肉"]),

    food("beef_round","牛もも","ぎゅうもも","Beef Round","肉類",
         182,21.3,10.6,0.5,0, vb2=0.22,vb6=0.35,vb12=2.0,nia=5.8,
         ca=4,mg=22,k=330,na=48,ph=190,fe=2.1,zn=4.4,se=11,
         effects={"muscles":{"score_contribution":0.9,"reason":"高タンパク・高亜鉛で筋肉修復を強力サポート"},
                  "brain":{"score_contribution":0.6,"reason":"B12・鉄が脳機能をサポート"}},
         tags=["高タンパク","亜鉛","鉄分"]),

    food("beef_liver","牛レバー","ぎゅうればー","Beef Liver","肉類",
         119,19.6,3.7,3.7,0, va=1100,vd=0,vb1=0.22,vb2=3.0,vb6=0.89,vb12=52,vc=30,
         fol=1000,pan=8.8, ca=5,mg=18,k=300,na=55,ph=330,fe=4.0,zn=3.3,cu=3.0,se=28,
         effects={"brain":{"score_contribution":0.9,"reason":"B12・葉酸・鉄が脳を強力サポート"},
                  "immune":{"score_contribution":0.8,"reason":"ビタミンAが免疫をサポート"},
                  "eyes":{"score_contribution":0.9,"reason":"ビタミンAが目をサポート"}},
         tags=["鉄分","B12","ビタミンA","貧血"]),

    food("lamb","ラム肉","らむにく","Lamb","肉類",
         235,19.8,17.1,0.3,0, vb1=0.15,vb2=0.27,vb6=0.26,vb12=2.9,nia=5.8,
         ca=9,mg=22,k=310,na=70,ph=200,fe=2.0,zn=3.5,se=7,
         func=[fi("carnitine","カルニチン","約200mg",["脂肪燃焼サポート","エネルギー産生","持久力向上"])],
         effects={"muscles":{"score_contribution":0.8,"reason":"カルニチン・タンパク質で筋肉エネルギーをサポート"}},
         craving={"has_signal":True,"message":"脂肪をエネルギーに変える力が落ちているサインかもしれません。カルニチンが豊富です"},
         tags=["カルニチン","脂肪燃焼","鉄分"]),

    # ── 魚介類 ──
    food("salmon","サーモン","さーもん","Salmon","魚介類",
         204,20.1,12.8,0.1,0, va=11,vd=33,ve=3.6,vb1=0.23,vb2=0.21,vb6=0.64,vb12=5.6,vc=4,
         nia=7.3,pan=1.6, ca=14,mg=27,k=370,na=66,ph=240,fe=0.5,zn=0.5,cu=0.06,se=40,
         func=[fi("dha","DHA","約820mg",["脳・神経機能維持","記憶力向上","中性脂肪低下"]),
               fi("epa","EPA","約492mg",["血液サラサラ","抗炎症","心疾患リスク低下"]),
               fi("astaxanthin","アスタキサンチン","約3mg",["強力抗酸化","目の疲れサポート","皮膚老化抑制"])],
         effects={"brain":{"score_contribution":0.9,"reason":"DHAが脳機能・記憶力をサポート"},
                  "eyes":{"score_contribution":0.8,"reason":"アスタキサンチンが目の疲れをサポート"},
                  "skin":{"score_contribution":0.7,"reason":"アスタキサンチンが皮膚老化抑制をサポート"},
                  "immune":{"score_contribution":0.6,"reason":"EPAが抗炎症作用をサポート"}},
         tips=[tip("緑黄色野菜","DHAの酸化を防ぐ可能性があります","ビタミンEがDHAの酸化を防ぐ")],
         tags=["DHA","EPA","アスタキサンチン","脳","目","抗酸化"]),

    food("tuna","マグロ","まぐろ","Tuna","魚介類",
         125,26.4,1.4,0.1,0, va=83,vd=4,ve=0.8,vb1=0.1,vb2=0.05,vb6=0.85,vb12=1.3,vc=2,
         nia=14.2,pan=0.9, ca=5,mg=45,k=380,na=49,ph=270,fe=1.1,zn=0.4,se=110,
         func=[fi("imidapeptide","イミダペプチド","約100mg",["疲労回復","抗酸化"]),
               fi("dha","DHA","約115mg",["脳機能維持","記憶力"]),
               fi("epa","EPA","約27mg",["血液サラサラ","抗炎症"])],
         effects={"brain":{"score_contribution":0.8,"reason":"DHAとイミダペプチドが脳疲労をサポート"},
                  "muscles":{"score_contribution":0.9,"reason":"超高タンパクで筋肉をサポート"},
                  "immune":{"score_contribution":0.6,"reason":"セレンが免疫をサポート"}},
         tags=["高タンパク","DHA","EPA","疲労回復","アスリート"]),

    food("mackerel","サバ","さば","Mackerel","魚介類",
         211,20.7,16.8,0.3,0, va=37,vd=11,ve=1.3,vb1=0.21,vb2=0.31,vb6=0.44,vb12=12.9,vc=1,
         nia=8.9, ca=6,mg=30,k=320,na=140,ph=220,fe=1.1,zn=1.1,se=43,
         func=[fi("dha","DHA","約970mg",["脳機能","記憶力","中性脂肪低下"]),
               fi("epa","EPA","約690mg",["血液サラサラ","抗炎症","コレステロール低下"])],
         effects={"brain":{"score_contribution":0.9,"reason":"DHA・EPAが脳を強力サポート"},
                  "immune":{"score_contribution":0.5,"reason":"EPAが抗炎症をサポート"},
                  "sleep":{"score_contribution":0.5,"reason":"B12・マグネシウムが睡眠をサポート"}},
         tags=["DHA","EPA","脳","青魚","血液サラサラ"]),

    food("sardine","イワシ","いわし","Sardine","魚介類",
         169,19.2,9.2,0.2,0, va=27,vd=32,ve=1.0,vb1=0.03,vb2=0.36,vb6=0.49,vb12=16,nia=7.7,
         ca=74,mg=30,k=270,na=150,ph=230,fe=2.1,zn=1.5,se=38,
         func=[fi("dha","DHA","約870mg",["脳機能","記憶力"]),
               fi("epa","EPA","約780mg",["血液サラサラ","抗炎症"])],
         effects={"brain":{"score_contribution":0.9,"reason":"DHAが脳機能を強力サポート"},
                  "bones":{"score_contribution":0.7,"reason":"カルシウム・ビタミンDが骨をサポート"},
                  "immune":{"score_contribution":0.6,"reason":"EPAが抗炎症をサポート"}},
         tips=[tip("大根おろし","消化を助ける可能性があります","大根の酵素が魚の脂質の消化をサポート")],
         tags=["DHA","EPA","カルシウム","骨","脳"]),

    food("bonito","カツオ","かつお","Bonito","魚介類",
         108,25.8,0.5,0.1,0, va=5,vd=4,vb1=0.13,vb2=0.17,vb6=0.76,vb12=8.4,nia=19.0,
         ca=11,mg=42,k=430,na=43,ph=280,fe=1.9,zn=0.8,se=100,
         func=[fi("imidapeptide","イミダペプチド","約200mg",["脳疲労回復","抗酸化","持久力向上"])],
         effects={"brain":{"score_contribution":0.9,"reason":"イミダペプチドが脳疲労を強力サポート"},
                  "muscles":{"score_contribution":0.8,"reason":"高タンパク・ナイアシンが筋肉をサポート"}},
         tags=["イミダペプチド","脳疲労","高タンパク","疲労回復"]),

    food("eel","ウナギ","うなぎ","Eel","魚介類",
         255,17.1,19.3,0.3,0, va=2400,vd=18,ve=7.4,vb1=0.75,vb2=0.74,vb6=0.13,vb12=5,
         ca=130,mg=20,k=230,na=74,ph=260,fe=0.5,zn=1.4,se=22,
         func=[fi("dha","DHA","約742mg",["脳機能","記憶力"]),
               fi("epa","EPA","約742mg",["血液サラサラ"])],
         effects={"brain":{"score_contribution":0.9,"reason":"ビタミンB1・DHAが脳疲労をサポート"},
                  "eyes":{"score_contribution":1.0,"reason":"ビタミンAが目を強力サポート"},
                  "skin":{"score_contribution":0.8,"reason":"ビタミンA・Eが肌をサポート"},
                  "bones":{"score_contribution":0.7,"reason":"ビタミンD・カルシウムが骨をサポート"}},
         tags=["スタミナ","ビタミンA","DHA","目","肌"]),

    food("oyster","カキ（牡蠣）","かき","Oyster","魚介類",
         60,6.9,2.2,4.9,0, va=30,vd=0,vb1=0.07,vb2=0.14,vb6=0.05,vb12=28,vc=3,
         fol=39, ca=88,mg=65,k=190,na=530,ph=100,fe=2.1,zn=14.5,cu=1.04,se=34,
         effects={"brain":{"score_contribution":0.8,"reason":"亜鉛・B12が脳神経をサポート"},
                  "immune":{"score_contribution":0.9,"reason":"亜鉛が免疫機能を強力サポート"},
                  "skin":{"score_contribution":0.7,"reason":"亜鉛が皮膚の再生をサポート"}},
         tips=[tip("レモン","亜鉛の吸収が高まる可能性があります","ビタミンCが亜鉛の吸収を促進")],
         tags=["亜鉛","B12","免疫","海のミルク"]),

    food("shijimi","シジミ","しじみ","Corbicula","魚介類",
         64,7.5,1.4,4.5,0, va=330,vb1=0.02,vb2=0.44,vb6=0.08,vb12=68,
         ca=240,mg=11,k=83,na=180,ph=120,fe=8.3,zn=2.1,
         effects={"brain":{"score_contribution":0.8,"reason":"B12・鉄が脳機能をサポート"},
                  "gut":{"score_contribution":0.6,"reason":"肝臓・腸の働きをサポートする可能性があります"}},
         tags=["B12","鉄分","肝臓","二日酔い"]),

    food("clam","アサリ","あさり","Clam","魚介類",
         27,6.0,0.6,0.4,0, va=4,vb1=0.02,vb2=0.16,vb12=52,nia=1.5,
         ca=66,mg=100,k=140,na=870,ph=85,fe=3.8,zn=1.0,
         effects={"brain":{"score_contribution":0.7,"reason":"鉄・B12が脳機能をサポート"},
                  "immune":{"score_contribution":0.5,"reason":"鉄が免疫をサポート"}},
         tags=["鉄分","B12","マグネシウム"]),

    # ── 野菜類 ──
    food("spinach","ほうれん草","ほうれんそう","Spinach","野菜類",
         18,2.2,0.4,2.8,2.8, va=350,vd=0,ve=2.1,vk=270,vb1=0.11,vb2=0.2,vb6=0.14,vc=35,
         fol=210,pan=0.57, ca=49,mg=69,k=690,na=16,ph=47,fe=2.0,zn=0.7,cu=0.11,mn=0.32,
         func=[fi("lutein","ルテイン","約12mg",["目の黄斑保護","目の疲れサポート","抗酸化"])],
         effects={"eyes":{"score_contribution":0.9,"reason":"ルテインが目の黄斑を強力サポート"},
                  "brain":{"score_contribution":0.6,"reason":"鉄・葉酸が脳機能をサポート"},
                  "immune":{"score_contribution":0.5,"reason":"ビタミンCが免疫をサポート"},
                  "bones":{"score_contribution":0.6,"reason":"ビタミンKがカルシウム代謝をサポート"}},
         tips=[tip("ごま油","ルテインの吸収が高まる可能性があります","ルテインは脂溶性で油と一緒に摂ると吸収される")],
         tags=["ルテイン","鉄分","葉酸","目","緑黄色野菜"]),

    food("komatsuna","小松菜","こまつな","Japanese Mustard Spinach","野菜類",
         13,1.5,0.2,2.4,1.9, va=260,ve=0.9,vk=210,vb1=0.09,vb2=0.13,vc=39,
         fol=110, ca=170,mg=12,k=500,na=15,ph=45,fe=2.8,mn=0.18,
         effects={"bones":{"score_contribution":0.8,"reason":"カルシウムが豊富で骨をサポート"},
                  "eyes":{"score_contribution":0.6,"reason":"ビタミンAが目をサポート"},
                  "immune":{"score_contribution":0.5,"reason":"ビタミンCが免疫をサポート"}},
         tags=["カルシウム","鉄分","緑黄色野菜"]),

    food("kale","ケール","けーる","Kale","野菜類",
         28,2.1,0.4,5.6,3.7, va=300,ve=2.4,vk=210,vb1=0.06,vb2=0.15,vb6=0.16,vc=81,
         fol=120, ca=220,mg=44,k=420,na=60,ph=45,fe=0.8,zn=0.4,cu=0.07,
         func=[fi("quercetin","ケルセチン","約45mg",["抗酸化","抗炎症","免疫サポート"])],
         effects={"immune":{"score_contribution":0.9,"reason":"ビタミンC・ケルセチンが免疫を強力サポート"},
                  "bones":{"score_contribution":0.8,"reason":"カルシウム・ビタミンKが骨をサポート"},
                  "eyes":{"score_contribution":0.7,"reason":"ビタミンAが目をサポート"},
                  "skin":{"score_contribution":0.6,"reason":"ビタミンC・Eが肌をサポート"}},
         tags=["スーパーフード","カルシウム","ビタミンK","免疫"]),

    food("broccoli","ブロッコリー","ぶろっこりー","Broccoli","野菜類",
         37,4.3,0.5,6.6,4.4, va=81,ve=3.0,vk=160,vb1=0.17,vb2=0.23,vb6=0.3,vc=120,
         fol=210,pan=1.4, ca=50,mg=29,k=360,na=20,ph=89,fe=1.3,zn=0.8,se=3,
         func=[fi("quercetin","ケルセチン","約3mg",["抗酸化","抗炎症"])],
         effects={"immune":{"score_contribution":0.9,"reason":"ビタミンCが免疫を強力サポート"},
                  "skin":{"score_contribution":0.7,"reason":"ビタミンC・Eが肌をサポート"},
                  "bones":{"score_contribution":0.5,"reason":"ビタミンK・カルシウムが骨をサポート"}},
         tips=[tip("オリーブオイル","脂溶性ビタミンの吸収が高まる可能性があります","ビタミンKは脂溶性で油と合わせると吸収率UP")],
         tags=["ビタミンC","葉酸","免疫","緑黄色野菜"]),

    food("tomato","トマト","とまと","Tomato","野菜類",
         20,0.7,0.1,4.7,1.0, va=45,ve=0.9,vk=4,vb1=0.05,vb6=0.09,vc=15,fol=22,
         ca=7,mg=9,k=210,na=3,ph=26,fe=0.2,
         func=[fi("lycopene","リコピン","約3mg",["強力抗酸化","心血管保護","皮膚老化抑制"])],
         effects={"skin":{"score_contribution":0.8,"reason":"リコピンが皮膚の老化抑制をサポート"},
                  "immune":{"score_contribution":0.5,"reason":"リコピン・ビタミンCが免疫をサポート"}},
         tips=[tip("オリーブオイル","リコピンの吸収が10倍以上高まる可能性があります","リコピンは脂溶性で加熱・油調理で吸収率が大幅UP"),
               tip("加熱調理","リコピンが増加します","加熱するとリコピンの吸収率が向上")],
         tags=["リコピン","抗酸化","肌","心血管"]),

    food("carrot","にんじん","にんじん","Carrot","野菜類",
         39,0.7,0.2,9.3,2.8, va=900,ve=0.5,vk=17,vb1=0.07,vb6=0.1,vc=6,fol=23,
         ca=28,mg=10,k=270,na=24,ph=25,fe=0.2,
         effects={"eyes":{"score_contribution":0.9,"reason":"βカロテン（ビタミンA）が目を強力サポート"},
                  "skin":{"score_contribution":0.7,"reason":"ビタミンAが肌の再生をサポート"},
                  "immune":{"score_contribution":0.6,"reason":"ビタミンAが免疫をサポート"}},
         tips=[tip("油炒め","βカロテンの吸収が4倍以上高まる可能性があります","βカロテンは脂溶性で油調理で吸収率大幅UP")],
         tags=["βカロテン","ビタミンA","目","肌","免疫"]),

    food("garlic","にんにく","にんにく","Garlic","野菜類",
         136,6.4,0.9,27.5,6.2, vb1=0.19,vb6=1.53,vc=10,fol=93,
         ca=14,mg=25,k=530,na=8,ph=150,fe=0.8,zn=0.8,
         func=[fi("quercetin","ケルセチン","約3mg",["抗酸化","抗炎症","免疫サポート"])],
         effects={"immune":{"score_contribution":0.9,"reason":"アリシン・ケルセチンが免疫を強力サポート"},
                  "brain":{"score_contribution":0.5,"reason":"ビタミンB6が脳機能をサポート"}},
         tips=[tip("豚肉","ビタミンB1の吸収が高まる可能性があります","アリシンがビタミンB1の体内利用率を大幅UP")],
         tags=["アリシン","免疫","抗菌","抗酸化"]),

    food("ginger","しょうが","しょうが","Ginger","野菜類",
         30,0.9,0.3,6.6,2.1, vc=2, ca=12,mg=27,k=270,na=6,ph=25,fe=0.5,
         func=[fi("quercetin","ショウガオール/ジンゲロール","少量",["抗酸化","抗炎症","体温上昇"])],
         effects={"immune":{"score_contribution":0.6,"reason":"ジンゲロールが免疫・抗炎症をサポート"},
                  "gut":{"score_contribution":0.5,"reason":"消化器官の働きをサポートする可能性があります"}},
         tags=["抗炎症","体温","消化","冷え性"]),

    food("avocado","アボカド","あぼかど","Avocado","果実類",
         187,2.5,18.7,7.9,5.6, va=7,ve=3.3,vk=20,vb1=0.1,vb2=0.21,vb6=0.32,vc=15,fol=83,pan=1.5,
         ca=9,mg=33,k=720,na=7,ph=55,fe=0.7,cu=0.24,mn=0.16,
         func=[fi("quercetin","ルテイン","約0.3mg",["目の健康サポート"])],
         effects={"brain":{"score_contribution":0.7,"reason":"良質な脂質・葉酸が脳をサポート"},
                  "skin":{"score_contribution":0.8,"reason":"ビタミンE・良質脂質が肌をサポート"},
                  "gut":{"score_contribution":0.7,"reason":"食物繊維が腸内環境をサポート"}},
         tags=["健康的脂質","葉酸","食物繊維","肌","脳"]),

    food("sweet_potato","さつまいも","さつまいも","Sweet Potato","いも類",
         132,1.2,0.2,30.3,2.2, va=0,ve=1.5,vk=0,vb1=0.1,vb6=0.26,vc=29,fol=49,pan=0.9,
         ca=36,mg=24,k=470,na=11,ph=46,fe=0.5,
         effects={"gut":{"score_contribution":0.7,"reason":"食物繊維・オリゴ糖が腸内環境をサポート"},
                  "skin":{"score_contribution":0.5,"reason":"ビタミンEが肌をサポート"},
                  "immune":{"score_contribution":0.4,"reason":"ビタミンCが免疫をサポート"}},
         tips=[tip("バター","ビタミンEの吸収が高まる可能性があります","脂溶性ビタミンEは脂質と一緒に吸収される")],
         tags=["食物繊維","腸活","エネルギー","ビタミンC"]),

    food("pumpkin","かぼちゃ","かぼちゃ","Pumpkin","野菜類",
         91,1.9,0.3,20.6,3.5, va=330,ve=4.9,vk=7,vb1=0.07,vb6=0.16,vc=43,fol=75,
         ca=15,mg=25,k=450,na=1,ph=43,fe=0.5,
         effects={"eyes":{"score_contribution":0.8,"reason":"βカロテンが目をサポート"},
                  "skin":{"score_contribution":0.8,"reason":"ビタミンE・Aが肌をサポート"},
                  "immune":{"score_contribution":0.6,"reason":"ビタミンC・Aが免疫をサポート"}},
         tags=["βカロテン","ビタミンE","目","肌","免疫"]),

    food("edamame","枝豆","えだまめ","Edamame","豆類",
         135,11.5,6.2,8.8,5.0, va=25,ve=0.7,vk=29,vb1=0.24,vb2=0.15,vb6=0.1,vc=27,fol=320,
         ca=58,mg=62,k=490,na=1,ph=170,fe=2.7,zn=1.4,
         effects={"brain":{"score_contribution":0.6,"reason":"葉酸・鉄が脳機能をサポート"},
                  "muscles":{"score_contribution":0.7,"reason":"植物性タンパク質・亜鉛が筋肉をサポート"},
                  "gut":{"score_contribution":0.5,"reason":"食物繊維が腸内環境をサポート"}},
         tags=["葉酸","植物性タンパク","亜鉛","鉄分"]),

    food("broccoli_sprouts","ブロッコリースプラウト","ぶろっこりーすぷらうと","Broccoli Sprouts","野菜類",
         21,2.1,0.3,3.9,1.8, vc=64, ca=57,mg=26,k=100,ph=72,fe=0.7,
         func=[fi("quercetin","スルフォラファン","高含有",["解毒酵素活性化","抗酸化","免疫サポート"])],
         effects={"immune":{"score_contribution":1.0,"reason":"スルフォラファンが解毒・免疫を強力サポート"},
                  "gut":{"score_contribution":0.7,"reason":"スルフォラファンが腸の解毒をサポート"}},
         tags=["スルフォラファン","デトックス","免疫","スーパーフード"],ref=True,src="reference"),

    # ── 果物類 ──
    food("banana","バナナ","ばなな","Banana","果実類",
         93,1.1,0.2,21.4,1.1, va=5,ve=0.5,vb1=0.05,vb2=0.04,vb6=0.34,vc=16,fol=26,pan=0.44,
         ca=6,mg=32,k=360,na=0,ph=27,fe=0.3,
         effects={"brain":{"score_contribution":0.6,"reason":"ビタミンB6・マグネシウムが脳機能をサポート"},
                  "sleep":{"score_contribution":0.5,"reason":"マグネシウム・トリプトファンが睡眠をサポート"},
                  "muscles":{"score_contribution":0.5,"reason":"カリウムが筋肉機能をサポート"}},
         craving={"has_signal":True,"message":"マグネシウムや炭水化物エネルギーが不足しているサインかもしれません"},
         tags=["エネルギー","B6","マグネシウム","カリウム","運動後"]),

    food("blueberry","ブルーベリー","ぶるーべりー","Blueberry","果実類",
         49,0.5,0.1,12.5,3.3, va=0,ve=1.7,vc=9,fol=11,
         ca=8,mg=5,k=70,ph=9,
         func=[fi("quercetin","アントシアニン","約165mg",["目の疲れサポート","強力抗酸化","脳機能サポート"]),
               fi("lutein","ルテイン","少量",["目の黄斑保護"])],
         effects={"eyes":{"score_contribution":0.9,"reason":"アントシアニンが目の疲れを強力サポート"},
                  "brain":{"score_contribution":0.7,"reason":"アントシアニンが脳の老化抑制をサポート"},
                  "skin":{"score_contribution":0.6,"reason":"強力抗酸化が肌の老化抑制をサポート"}},
         tags=["アントシアニン","目","脳","抗酸化","スーパーフード"]),

    food("strawberry","いちご","いちご","Strawberry","果実類",
         34,0.9,0.1,8.5,1.4, ve=0.4,vk=4,vb1=0.03,vb2=0.05,vc=62,fol=90,
         ca=17,mg=13,k=170,ph=31,fe=0.3,
         effects={"immune":{"score_contribution":0.8,"reason":"ビタミンCが免疫を強力サポート"},
                  "skin":{"score_contribution":0.7,"reason":"ビタミンCがコラーゲン生成をサポート"}},
         tags=["ビタミンC","葉酸","免疫","肌"]),

    food("lemon","レモン","れもん","Lemon","果実類",
         54,0.9,0.7,12.5,4.9, ve=1.6,vb1=0.07,vb2=0.07,vc=100,fol=31,pan=0.4,
         ca=67,mg=11,k=130,na=4,ph=15,fe=0.2,
         effects={"immune":{"score_contribution":0.9,"reason":"ビタミンCが免疫を強力サポート"},
                  "skin":{"score_contribution":0.7,"reason":"ビタミンCがコラーゲン合成をサポート"}},
         tips=[tip("鉄分食材（ほうれん草など）","鉄の吸収率が大幅に高まる可能性があります","ビタミンCが非ヘム鉄の吸収を大幅促進")],
         tags=["ビタミンC","免疫","肌","鉄吸収促進"]),

    food("acerola","アセロラ","あせろら","Acerola","果実類",
         36,0.7,0.1,9.0,1.9, vc=1700,fol=13,
         ca=11,mg=10,k=130,fe=0.2,
         effects={"immune":{"score_contribution":1.0,"reason":"ビタミンCを超大量含み免疫を最強サポート"},
                  "skin":{"score_contribution":0.9,"reason":"ビタミンCがコラーゲン生成を強力サポート"}},
         tags=["ビタミンC最高量","免疫","肌","スーパーフード"],ref=True,src="reference"),

    food("pomegranate","ざくろ","ざくろ","Pomegranate","果実類",
         83,1.7,0.6,17.0,0, vc=10,fol=49,
         ca=8,mg=13,k=290,fe=0.4,
         func=[fi("quercetin","プニカラジン/エラグ酸","高含有",["強力抗酸化","抗炎症","腸内環境サポート"])],
         effects={"gut":{"score_contribution":0.7,"reason":"ポリフェノールが腸内環境をサポート"},
                  "skin":{"score_contribution":0.6,"reason":"エラグ酸が肌の老化抑制をサポート"},
                  "immune":{"score_contribution":0.5,"reason":"抗酸化成分が免疫をサポート"}},
         tags=["エラグ酸","抗酸化","腸活","肌"],ref=True,src="reference"),

    # ── 豆・大豆製品 ──
    food("natto","納豆","なっとう","Natto","豆類",
         200,16.5,10.0,12.1,6.7, vd=0,ve=0.3,vk=870,vb1=0.07,vb2=0.56,vb6=0.24,vb12=0,
         fol=120,pan=3.6,bio=10, ca=90,mg=100,k=660,na=2,ph=190,fe=3.3,zn=1.9,cu=0.55,mn=1.73,
         func=[fi("lactic_acid_bacteria","ナットウキナーゼ","約2000FU",["血液サラサラ","血栓溶解","腸内環境改善"]),
               fi("beta_glucan","イソフラボン","約75mg",["骨粗鬆症予防サポート","女性ホルモン様作用"])],
         effects={"gut":{"score_contribution":0.9,"reason":"ナットウキナーゼ・食物繊維が腸を強力サポート"},
                  "bones":{"score_contribution":0.8,"reason":"ビタミンK2・カルシウムが骨をサポート"},
                  "immune":{"score_contribution":0.6,"reason":"腸内環境改善が免疫をサポート"}},
         tips=[tip("キムチ","腸内環境への効果が高まる可能性があります","善玉菌が相乗効果でさらに増える可能性あり")],
         tags=["ナットウキナーゼ","ビタミンK2","腸活","発酵食品","骨"]),

    food("tofu_firm","木綿豆腐","もめんとうふ","Firm Tofu","豆類",
         73,7.0,4.9,1.5,0.4, vd=0,ve=0.1,vk=4,vb1=0.1,vb2=0.05,vb6=0.05,
         ca=93,mg=57,k=110,na=2,ph=99,fe=1.5,zn=0.6,
         func=[fi("beta_glucan","大豆イソフラボン","約25mg",["骨粗鬆症予防サポート","女性ホルモン様作用"])],
         effects={"bones":{"score_contribution":0.7,"reason":"カルシウム・イソフラボンが骨をサポート"},
                  "muscles":{"score_contribution":0.6,"reason":"植物性タンパク質が筋肉をサポート"}},
         tags=["イソフラボン","カルシウム","植物性タンパク","骨"]),

    food("miso","味噌","みそ","Miso","豆類",
         186,12.5,6.0,21.9,4.9, vd=0,ve=0,vk=0,vb1=0.03,vb2=0.1,vb6=0.12,vb12=0,
         fol=19,pan=0.53, ca=100,mg=75,k=380,na=4900,ph=170,fe=3.0,zn=0.9,cu=0.36,mn=1.3,
         func=[fi("lactic_acid_bacteria","麹菌・乳酸菌","豊富",["腸内環境改善","免疫サポート","消化促進"])],
         effects={"gut":{"score_contribution":0.8,"reason":"麹菌・乳酸菌が腸内環境をサポート"},
                  "immune":{"score_contribution":0.6,"reason":"腸内環境改善を通じて免疫をサポート"}},
         tags=["発酵食品","麹菌","腸活","免疫","塩分注意"]),

    food("yogurt","ヨーグルト","よーぐると","Yogurt","乳類",
         62,3.6,3.0,4.9,0, vd=0,ve=0,vb1=0.04,vb2=0.14,vb12=0.4,pan=0.49,bio=2.5,
         ca=120,mg=12,k=170,na=48,ph=100,
         func=[fi("lactic_acid_bacteria","乳酸菌","豊富",["腸内環境改善","免疫サポート","便秘改善"]),
               fi("beta_glucan","プロバイオティクス","豊富",["腸内フローラ改善"])],
         effects={"gut":{"score_contribution":0.9,"reason":"乳酸菌が腸内環境を強力サポート"},
                  "immune":{"score_contribution":0.7,"reason":"腸内環境改善が免疫をサポート"},
                  "bones":{"score_contribution":0.7,"reason":"カルシウムが骨をサポート"},
                  "sleep":{"score_contribution":0.4,"reason":"トリプトファンが睡眠をサポートする可能性があります"}},
         tips=[tip("バナナ・はちみつ","乳酸菌が増えやすくなる可能性があります","オリゴ糖が善玉菌のエサになる")],
         tags=["乳酸菌","カルシウム","腸活","免疫","プロバイオティクス"]),

    food("kefir","ケフィア","けふぃあ","Kefir","乳類",
         65,3.8,3.5,4.6,0, vd=0,vb1=0.04,vb2=0.16,vb12=0.5,
         ca=120,mg=14,k=150,na=50,ph=95,
         func=[fi("lactic_acid_bacteria","乳酸菌・酵母菌","超豊富",["腸内環境改善","免疫強化","精神安定サポート"]),
               fi("gaba","GABA","少量",["ストレス緩和","睡眠サポート"])],
         effects={"gut":{"score_contribution":1.0,"reason":"多種の乳酸菌・酵母が腸を最強サポート"},
                  "immune":{"score_contribution":0.8,"reason":"多様な菌が免疫を強力サポート"},
                  "sleep":{"score_contribution":0.5,"reason":"GABAが睡眠をサポートする可能性があります"}},
         tags=["スーパープロバイオティクス","腸活","免疫","発酵食品"],ref=True,src="reference"),

    # ── きのこ類 ──
    food("shiitake","しいたけ","しいたけ","Shiitake Mushroom","きのこ類",
         34,3.0,0.4,6.4,4.2, vd=0.4,vb1=0.1,vb2=0.22,vb6=0.1,vc=0,nia=3.8,fol=49,pan=1.54,bio=21,
         ca=2,mg=14,k=270,na=2,ph=62,fe=0.3,zn=0.5,cu=0.21,mn=0.19,
         func=[fi("beta_glucan","β-グルカン（レンチナン）","豊富",["免疫活性化","抗腫瘍サポート","腸内環境改善"])],
         effects={"immune":{"score_contribution":0.9,"reason":"β-グルカンが免疫細胞を強力サポート"},
                  "gut":{"score_contribution":0.6,"reason":"食物繊維・β-グルカンが腸をサポート"},
                  "bones":{"score_contribution":0.5,"reason":"ビタミンDが骨をサポート（日光干しで増加）"}},
         tips=[tip("日光に当てる（干し椎茸）","ビタミンDが大幅増加します","紫外線でビタミンDが生成される")],
         tags=["β-グルカン","免疫","ビタミンD","腸活"]),

    food("maitake","まいたけ","まいたけ","Maitake Mushroom","きのこ類",
         22,2.0,0.5,3.8,3.5, vd=4.9,vb1=0.09,vb2=0.29,nia=5.8,fol=59,pan=1.47,
         ca=1,mg=10,k=230,ph=54,
         func=[fi("beta_glucan","β-グルカン（Dフラクション）","豊富",["強力免疫活性化","血糖値サポート"])],
         effects={"immune":{"score_contribution":1.0,"reason":"Dフラクションが免疫を最強サポート"},
                  "gut":{"score_contribution":0.6,"reason":"食物繊維が腸をサポート"}},
         tags=["β-グルカン","免疫","Dフラクション","ダイエット"]),

    food("lions_mane","ヤマブシタケ","やまぶしたけ","Lion's Mane Mushroom","きのこ類",
         27,2.2,0.4,5.0,4.4,
         func=[fi("beta_glucan","ヘリセノン・エリナシン","豊富",["神経成長因子産生サポート","記憶力サポート","認知機能サポート"])],
         effects={"brain":{"score_contribution":1.0,"reason":"ヘリセノンが神経成長因子産生をサポートし記憶力をサポート"},
                  "gut":{"score_contribution":0.5,"reason":"食物繊維が腸をサポート"}},
         tags=["神経成長因子","記憶力","脳","スーパーフード"],ref=True,src="reference"),

    food("reishi","霊芝","れいし","Reishi Mushroom","きのこ類",
         0,0,0,0,0,
         func=[fi("beta_glucan","ガノデルマン酸","豊富",["免疫調整","ストレス耐性サポート","抗酸化"])],
         effects={"immune":{"score_contribution":0.9,"reason":"トリテルペンが免疫調整をサポート"},
                  "sleep":{"score_contribution":0.7,"reason":"ストレス緩和を通じて睡眠をサポート"}},
         tags=["免疫調整","アダプトゲン","睡眠","抗酸化"],ref=True,src="reference"),

    food("chaga","チャーガ","ちゃーが","Chaga Mushroom","きのこ類",
         0,0,0,0,0,
         func=[fi("beta_glucan","β-グルカン・ベツリン酸","超豊富",["強力抗酸化","免疫サポート"])],
         effects={"immune":{"score_contribution":0.9,"reason":"ベツリン酸・β-グルカンが免疫をサポート"},
                  "skin":{"score_contribution":0.6,"reason":"SOD（抗酸化酵素）が肌の老化抑制をサポート"}},
         tags=["抗酸化王","免疫","スーパーフード"],ref=True,src="reference"),

    # ── 海藻類 ──
    food("hijiki","ひじき","ひじき","Hijiki Seaweed","藻類",
         180,10.6,1.3,58.4,54.9, vd=0,vb2=0.18,vc=0,
         ca=1400,mg=620,k=4400,na=1800,ph=93,fe=58.2,zn=1.0,cu=0.2,io=45000,
         effects={"bones":{"score_contribution":0.9,"reason":"カルシウム・マグネシウムが骨を強力サポート"},
                  "gut":{"score_contribution":0.8,"reason":"豊富な食物繊維が腸をサポート"}},
         tags=["カルシウム","鉄分","ミネラル","腸活","骨"]),

    food("wakame","わかめ","わかめ","Wakame Seaweed","藻類",
         16,1.9,0.2,2.0,3.6, va=56,vd=0,vb2=0.18,
         ca=100,mg=110,k=730,na=610,ph=35,fe=0.7,io=3500,
         func=[fi("quercetin","フコキサンチン","少量",["脂肪燃焼サポート","抗酸化","抗炎症"])],
         effects={"gut":{"score_continuation":0.7,"reason":"フコイダン・食物繊維が腸をサポート"},
                  "bones":{"score_contribution":0.6,"reason":"カルシウム・マグネシウムが骨をサポート"}},
         tags=["フコイダン","カルシウム","腸活","ダイエット"]),

    food("nori","焼き海苔","やきのり","Dried Nori Seaweed","藻類",
         188,41.4,3.7,44.3,36.0, va=2300,vd=0,ve=4.6,vb1=0.69,vb2=2.68,vb12=57.6,vc=210,
         fol=1900, ca=280,mg=300,k=2400,na=610,ph=700,fe=11.4,zn=3.6,io=2100,
         effects={"brain":{"score_contribution":0.8,"reason":"B12・葉酸が脳機能をサポート"},
                  "immune":{"score_contribution":0.7,"reason":"ビタミンC・Aが免疫をサポート"},
                  "bones":{"score_contribution":0.6,"reason":"カルシウム・マグネシウムが骨をサポート"}},
         tags=["B12","葉酸","ビタミンC","鉄分","ミネラル"]),

    # ── ナッツ・種実 ──
    food("almond","アーモンド","あーもんど","Almond","種実類",
         608,19.6,51.8,19.7,10.1, va=0,ve=28.8,vk=0,vb1=0.24,vb2=0.92,vb6=0.06,vc=0,
         fol=49,pan=0.47,bio=8.4, ca=250,mg=270,k=740,na=0,ph=480,fe=4.7,zn=3.1,cu=1.12,mn=2.5,
         effects={"skin":{"score_contribution":0.9,"reason":"ビタミンEが肌の老化抑制を強力サポート"},
                  "bones":{"score_contribution":0.7,"reason":"カルシウム・マグネシウムが骨をサポート"},
                  "brain":{"score_contribution":0.5,"reason":"マグネシウムが脳神経をサポート"}},
         tags=["ビタミンE","マグネシウム","カルシウム","肌","骨"]),

    food("walnut","くるみ","くるみ","Walnut","種実類",
         713,14.6,68.8,11.7,7.5, ve=1.2,vb1=0.26,vb2=0.15,vb6=0.49,fol=91,pan=0.67,
         ca=85,mg=150,k=540,na=4,ph=280,fe=2.6,zn=2.6,cu=1.07,mn=3.44,
         func=[fi("dha","ALA（オメガ3前駆体）","約9000mg",["脳機能サポート","抗炎症","心血管サポート"])],
         effects={"brain":{"score_contribution":0.9,"reason":"オメガ3脂肪酸が脳を強力サポート"},
                  "immune":{"score_contribution":0.5,"reason":"オメガ3の抗炎症作用が免疫をサポート"},
                  "sleep":{"score_contribution":0.4,"reason":"マグネシウムが睡眠をサポート"}},
         tags=["オメガ3","脳","抗酸化","マグネシウム"]),

    food("chia_seed","チアシード","ちあしーど","Chia Seed","種実類",
         486,16.5,30.7,42.1,34.4, va=0,ve=0.5,vc=1.6,fol=49,
         ca=631,mg=335,k=407,na=16,ph=860,fe=7.7,zn=4.6,cu=0.92,mn=2.72,
         func=[fi("dha","ALA（オメガ3）","約17500mg",["脳・心血管サポート","抗炎症"])],
         effects={"gut":{"score_contribution":0.9,"reason":"豊富な食物繊維が腸を強力サポート"},
                  "bones":{"score_contribution":0.8,"reason":"カルシウム・マグネシウムが骨をサポート"},
                  "brain":{"score_contribution":0.7,"reason":"オメガ3が脳をサポート"}},
         tags=["オメガ3","食物繊維","カルシウム","スーパーフード","腸活"],ref=True,src="reference"),

    food("hemp_seed","ヘンプシード","へんぷしーど","Hemp Seed","種実類",
         553,31.6,49.4,8.7,4.0,
         ca=70,mg=700,k=1200,ph=1160,fe=8.0,zn=9.9,
         func=[fi("dha","GLA（ガンマリノレン酸）","約870mg",["抗炎症","PMS緩和サポート"])],
         effects={"muscles":{"score_contribution":0.8,"reason":"完全植物性タンパク（9種必須アミノ酸）が筋肉をサポート"},
                  "immune":{"score_contribution":0.6,"reason":"GLAが抗炎症をサポート"},
                  "brain":{"score_contribution":0.5,"reason":"オメガ3/6バランスが脳をサポート"}},
         tags=["完全タンパク","GLA","マグネシウム","スーパーフード"],ref=True,src="reference"),

    food("brazil_nut","ブラジルナッツ","ぶらじるなっつ","Brazil Nut","種実類",
         700,14.5,66.9,12.3,7.5, ve=5.7,vb1=0.62,vb6=0.1,fol=22,
         ca=160,mg=376,k=597,ph=725,fe=2.4,zn=4.1,se=1917,
         effects={"immune":{"score_contribution":0.9,"reason":"超高濃度セレンが免疫・甲状腺をサポート"},
                  "skin":{"score_contribution":0.7,"reason":"セレン・ビタミンEが肌をサポート"}},
         cook=["1日2粒が目安。食べすぎるとセレン過剰になる可能性があります"],
         tags=["セレン最高量","免疫","甲状腺","ナッツ"]),

    food("sesame","ごま（白）","ごましろ","White Sesame","種実類",
         605,20.3,53.8,18.5,10.8, vb1=0.49,vb2=0.23,vb6=0.64,fol=93,pan=0.51,
         ca=1200,mg=360,k=400,na=3,ph=540,fe=9.9,zn=5.9,cu=1.21,mn=2.14,
         func=[fi("collagen","セサミン","約800mg",["強力抗酸化","肝臓保護サポート","コレステロール管理サポート"])],
         effects={"bones":{"score_contribution":0.9,"reason":"カルシウムが骨を強力サポート"},
                  "skin":{"score_contribution":0.6,"reason":"セサミン・ビタミンEが肌をサポート"},
                  "gut":{"score_contribution":0.5,"reason":"食物繊維が腸をサポート"}},
         tips=[tip("すりごま","栄養素の吸収率が大幅に高まります","殻を砕くと内部の栄養素が吸収される")],
         tags=["カルシウム","セサミン","鉄分","骨","抗酸化"]),

    food("flaxseed","亜麻仁（フラックスシード）","あまにふらっくすしーど","Flaxseed","種実類",
         534,18.3,42.7,28.9,27.3, vb1=1.64,vb2=0.16,fol=87,
         ca=255,mg=392,k=813,ph=642,fe=5.7,zn=4.3,mn=2.48,
         func=[fi("dha","ALA（オメガ3）","約22800mg",["脳・心血管サポート","抗炎症","ホルモンバランスサポート"])],
         effects={"brain":{"score_contribution":0.8,"reason":"オメガ3が脳をサポート"},
                  "gut":{"score_contribution":0.8,"reason":"豊富な食物繊維が腸をサポート"},
                  "immune":{"score_contribution":0.5,"reason":"オメガ3の抗炎症が免疫をサポート"}},
         tips=[tip("すり潰して摂取","栄養吸収率が大幅UP","そのままでは消化されにくいため粉砕が推奨")],
         tags=["オメガ3最高量","食物繊維","脳","腸活","スーパーフード"],ref=True,src="reference"),

    # ── スーパーフード ──
    food("spirulina","スピルリナ","すぴるりな","Spirulina","藻類",
         290,57.0,8.0,24.0,8.0, va=342,ve=5.0,vb1=0.35,vb2=3.67,vb6=0.36,vb12=0.2,vc=10,
         fol=94,pan=3.46, ca=120,mg=192,k=1363,fe=28.5,zn=2.0,cu=0.61,mn=1.9,
         func=[fi("beta_glucan","フィコシアニン","豊富",["強力抗酸化","免疫活性化","抗炎症サポート"])],
         effects={"immune":{"score_contribution":0.9,"reason":"フィコシアニン・β-カロテンが免疫を強力サポート"},
                  "brain":{"score_contribution":0.6,"reason":"B12・鉄が脳機能をサポート"},
                  "muscles":{"score_contribution":0.7,"reason":"高タンパク・鉄が筋肉をサポート"}},
         tags=["スーパーフード","タンパク","鉄分","フィコシアニン","免疫"],ref=True,src="reference"),

    food("maca","マカ","まか","Maca","スーパーフード",
         325,14.0,2.2,71.0,8.5,
         ca=450,mg=104,k=2050,ph=440,fe=25.0,zn=3.8,
         effects={"muscles":{"score_contribution":0.6,"reason":"ミネラルが筋肉機能をサポート"},
                  "sleep":{"score_contribution":0.5,"reason":"ストレス耐性サポートを通じて睡眠をサポート"}},
         craving={"has_signal":True,"message":"エネルギーや性ホルモンバランスのサポートが必要なサインかもしれません"},
         tags=["アダプトゲン","スタミナ","ホルモンバランス","スーパーフード"],ref=True,src="reference"),

    food("goji_berry","ゴジベリー（クコの実）","ごじべりー","Goji Berry","果実類",
         349,14.3,0.4,77.1,7.0, va=1625,vc=48,
         ca=112,mg=96,k=1132,fe=6.8,zn=1.98,
         func=[fi("quercetin","ゼアキサンチン","約2000μg",["目の黄斑保護","強力抗酸化"])],
         effects={"eyes":{"score_contribution":1.0,"reason":"ゼアキサンチンが目の黄斑を最強サポート"},
                  "immune":{"score_contribution":0.8,"reason":"ビタミンA・Cが免疫をサポート"},
                  "skin":{"score_contribution":0.6,"reason":"抗酸化成分が肌をサポート"}},
         tags=["ゼアキサンチン","目","スーパーフード","抗酸化"],ref=True,src="reference"),

    food("cacao_nibs","カカオニブ","かかおにぶ","Cacao Nibs","スーパーフード",
         456,13.0,46.0,34.0,14.0, ve=0.3,
         ca=128,mg=499,k=1524,ph=734,fe=6.3,zn=3.3,cu=1.76,mn=3.84,
         func=[fi("quercetin","テオブロミン・フラボノール","豊富",["抗酸化","気分向上サポート","心血管サポート"])],
         effects={"brain":{"score_contribution":0.7,"reason":"テオブロミン・マグネシウムが脳をサポート"},
                  "muscles":{"score_contribution":0.5,"reason":"マグネシウムが筋肉をサポート"},
                  "immune":{"score_contribution":0.5,"reason":"抗酸化フラボノールが免疫をサポート"}},
         craving={"has_signal":True,"message":"マグネシウム不足やストレス・疲労のサインかもしれません"},
         tags=["マグネシウム","抗酸化","テオブロミン","脳","スーパーフード"],ref=True,src="reference"),

    food("moringa","モリンガ","もりんが","Moringa","スーパーフード",
         64,9.4,1.4,8.3,2.0, va=378,vc=51,fol=40,
         ca=185,mg=42,k=337,ph=112,fe=4.0,zn=0.6,
         effects={"immune":{"score_contribution":0.8,"reason":"豊富なビタミン・ミネラルが免疫をサポート"},
                  "eyes":{"score_contribution":0.7,"reason":"ビタミンAが目をサポート"},
                  "bones":{"score_contribution":0.6,"reason":"カルシウムが骨をサポート"}},
         tags=["スーパーフード","栄養密度","ビタミンA","免疫"],ref=True,src="reference"),

    # ── ハーブ・アダプトゲン ──
    food("ashwagandha","アシュワガンダ","あしゅわがんだ","Ashwagandha","ハーブ類",
         0,0,0,0,0,
         func=[fi("quercetin","ウィサノライド","豊富",["ストレス耐性サポート","コルチゾール低下","睡眠改善サポート","筋力向上サポート"])],
         effects={"sleep":{"score_contribution":0.9,"reason":"ウィサノライドがストレス・睡眠を強力サポート"},
                  "muscles":{"score_contribution":0.7,"reason":"テストステロン様作用で筋力をサポートする可能性があります"},
                  "brain":{"score_contribution":0.6,"reason":"ストレス耐性サポートが脳機能をサポート"}},
         tags=["アダプトゲン","ストレス","睡眠","筋力","抗不安"],ref=True,src="reference"),

    food("chamomile","カモミール","かもみーる","Chamomile","ハーブ類",
         0,0,0,0,0,
         func=[fi("gaba","アピゲニン","豊富",["リラックスサポート","睡眠誘導サポート","抗不安"])],
         effects={"sleep":{"score_contribution":0.9,"reason":"アピゲニンがGABA受容体に作用し睡眠をサポート"},
                  "gut":{"score_contribution":0.5,"reason":"消化器官の炎症を鎮めるサポートをする可能性があります"}},
         tags=["睡眠","リラックス","不安","腸"],ref=True,src="reference"),

    food("elderberry","エルダーベリー","えるだーべりー","Elderberry","ハーブ類",
         73,0.7,0.5,18.4,7.0, vc=36,
         ca=38,ph=39,fe=1.6,
         func=[fi("quercetin","アントシアニン・フラボノイド","超豊富",["抗ウイルスサポート","免疫強化","抗炎症"])],
         effects={"immune":{"score_contribution":1.0,"reason":"抗ウイルス・免疫活性化を強力サポート"},
                  "skin":{"score_contribution":0.6,"reason":"抗酸化成分が肌をサポート"}},
         tags=["免疫最強","抗ウイルス","アントシアニン","風邪予防"],ref=True,src="reference"),

    food("turmeric","ターメリック（ウコン）","たーめりっく","Turmeric","スパイス類",
         354,8.5,4.7,72.0,21.1, vb6=1.80, ca=183,mg=193,k=2525,ph=268,fe=41.4,mn=7.83,
         func=[fi("quercetin","クルクミン","約3%",["強力抗炎症","抗酸化","肝臓保護サポート","脳機能サポート"])],
         effects={"gut":{"score_contribution":0.8,"reason":"クルクミンが腸の炎症抑制をサポート"},
                  "brain":{"score_contribution":0.7,"reason":"クルクミンが脳の炎症抑制・記憶力をサポート"},
                  "immune":{"score_contribution":0.7,"reason":"抗炎症作用が免疫をサポート"},
                  "skin":{"score_contribution":0.5,"reason":"抗酸化が肌をサポート"}},
         tips=[tip("ブラックペッパー","クルクミンの吸収率が2000%向上する可能性があります","ピペリンがクルクミンの吸収を劇的に促進"),
               tip("油","脂溶性クルクミンの吸収が高まる可能性があります","クルクミンは脂溶性で油と摂ると効果的")],
         tags=["クルクミン","抗炎症","抗酸化","脳","腸"]),

    # ── 穀類 ──
    food("brown_rice","玄米","げんまい","Brown Rice","穀類",
         165,2.8,1.0,35.6,1.4, ve=0.9,vk=0,vb1=0.16,vb2=0.02,vb6=0.21,nia=2.9,fol=10,pan=0.65,bio=2.5,
         ca=7,mg=49,k=95,na=1,ph=130,fe=0.6,zn=0.8,cu=0.13,mn=1.73,
         func=[fi("gaba","GABA","約10mg",["ストレス緩和","血圧サポート","睡眠サポート"])],
         effects={"brain":{"score_contribution":0.6,"reason":"ビタミンB1・GABAが脳エネルギー代謝をサポート"},
                  "gut":{"score_contribution":0.5,"reason":"食物繊維が腸をサポート"},
                  "sleep":{"score_contribution":0.4,"reason":"GABAが睡眠をサポートする可能性があります"}},
         tags=["GABA","ビタミンB1","食物繊維","全粒穀物"]),

    food("oatmeal","オートミール","おーとみーる","Oatmeal","穀類",
         350,13.7,5.7,69.1,9.4, vb1=0.35,vb2=0.1,vb6=0.13,fol=30,pan=0.96,bio=24,
         ca=47,mg=100,k=260,na=3,ph=370,fe=3.9,zn=3.0,cu=0.26,mn=3.9,
         func=[fi("beta_glucan","β-グルカン","約4g/100g",["腸内環境改善","血糖値サポート","コレステロール低下サポート"])],
         effects={"gut":{"score_contribution":0.9,"reason":"β-グルカンが腸を強力サポート"},
                  "bones":{"score_contribution":0.5,"reason":"カルシウム・マグネシウムが骨をサポート"},
                  "muscles":{"score_contribution":0.6,"reason":"タンパク質・亜鉛が筋肉をサポート"}},
         tags=["β-グルカン","食物繊維","腸活","血糖値"]),

    food("quinoa","キヌア","きぬあ","Quinoa","穀類",
         368,13.4,6.3,64.2,7.0, ve=2.4,vb1=0.36,vb2=0.32,vb6=0.49,fol=184,pan=0.77,
         ca=60,mg=210,k=740,ph=457,fe=4.6,zn=3.1,cu=0.59,mn=2.0,
         effects={"muscles":{"score_contribution":0.8,"reason":"完全タンパク（全必須アミノ酸）が筋肉をサポート"},
                  "gut":{"score_contribution":0.6,"reason":"食物繊維が腸をサポート"},
                  "bones":{"score_contribution":0.5,"reason":"マグネシウム・カルシウムが骨をサポート"}},
         tags=["完全タンパク","マグネシウム","グルテンフリー","スーパーグレイン"],ref=True,src="reference"),

    # ── 乳製品・卵 ──
    food("egg","鶏卵","けいらん","Egg","卵類",
         151,12.3,10.3,0.3,0, va=150,vd=2.5,ve=1.0,vk=11,vb1=0.06,vb2=0.43,vb6=0.08,vb12=1.1,
         fol=49,bio=25, ca=51,mg=10,k=130,na=140,ph=180,fe=1.8,zn=1.3,se=33,
         func=[fi("lutein","ルテイン・ゼアキサンチン","約252μg",["目の黄斑保護","目の疲れサポート"]),
               fi("collagen","コリン","約251mg",["脳機能・記憶力サポート","肝臓健康サポート"])],
         effects={"brain":{"score_contribution":0.8,"reason":"コリン・B12が脳機能を強力サポート"},
                  "eyes":{"score_contribution":0.7,"reason":"ルテインが目をサポート"},
                  "muscles":{"score_contribution":0.7,"reason":"完全タンパクが筋肉修復をサポート"}},
         tips=[tip("ビタミンC食材","鉄の吸収率が高まる可能性があります","ビタミンCが卵の非ヘム鉄吸収を促進")],
         tags=["完全栄養食","コリン","ルテイン","脳","筋肉"]),

    food("milk","牛乳","ぎゅうにゅう","Cow's Milk","乳類",
         67,3.3,3.8,4.8,0, va=39,vd=0.3,ve=0.1,vk=2,vb1=0.04,vb2=0.15,vb12=0.3,pan=0.55,bio=2,
         ca=110,mg=10,k=150,na=41,ph=93,fe=0,zn=0.4,io=17,
         effects={"bones":{"score_contribution":0.8,"reason":"カルシウム・ビタミンDが骨をサポート"},
                  "sleep":{"score_contribution":0.5,"reason":"トリプトファン・カルシウムが睡眠をサポートする可能性があります"},
                  "muscles":{"score_contribution":0.5,"reason":"タンパク質が筋肉をサポート"}},
         craving={"has_signal":True,"message":"カルシウム・ビタミンD不足のサインかもしれません"},
         tags=["カルシウム","タンパク","ビタミンD","骨","睡眠"]),

    # ── 発酵食品 ──
    food("kimchi","キムチ","きむち","Kimchi","発酵食品類",
         29,2.5,0.5,4.9,2.7, va=65,vc=19,
         ca=71,mg=18,k=370,na=870,ph=53,fe=0.7,
         func=[fi("lactic_acid_bacteria","乳酸菌（ラクトバチルス）","超豊富",["腸内フローラ改善","免疫強化","便秘改善サポート"])],
         effects={"gut":{"score_contribution":1.0,"reason":"豊富な乳酸菌が腸を最強サポート"},
                  "immune":{"score_contribution":0.8,"reason":"乳酸菌・カプサイシンが免疫をサポート"},
                  "skin":{"score_contribution":0.4,"reason":"ビタミンCが肌をサポート"}},
         tips=[tip("納豆","腸内環境への効果がさらに高まる可能性があります","異なる善玉菌が相乗効果")],
         tags=["乳酸菌","腸活","発酵食品","免疫","プロバイオティクス"]),

    food("kombucha","コンブチャ","こんぶちゃ","Kombucha","発酵食品類",
         16,0.2,0,3.5,0,
         func=[fi("lactic_acid_bacteria","有機酸・プロバイオティクス","豊富",["腸内環境改善","解毒サポート","免疫サポート"])],
         effects={"gut":{"score_contribution":0.8,"reason":"プロバイオティクス・有機酸が腸をサポート"},
                  "immune":{"score_contribution":0.6,"reason":"腸内環境改善が免疫をサポート"}},
         tags=["発酵食品","腸活","デトックス","プロバイオティクス"],ref=True,src="reference"),

    food("sake_lees","酒粕","さけかす","Sake Lees","発酵食品類",
         227,14.9,1.5,23.8,5.2, vb1=0.03,vb2=0.26,vb6=0.08,vb12=0,fol=170,pan=3.1,
         ca=8,mg=18,k=28,na=5,ph=100,fe=0.8,zn=2.1,
         func=[fi("lactic_acid_bacteria","レジスタントプロテイン","豊富",["腸内環境改善","脂肪吸収抑制サポート"])],
         effects={"gut":{"score_contribution":0.7,"reason":"食物繊維・レジスタントプロテインが腸をサポート"},
                  "skin":{"score_contribution":0.5,"reason":"アミノ酸が肌をサポートする可能性があります"}},
         tags=["発酵食品","腸活","葉酸","肌"]),

    # ── 油脂類 ──
    food("olive_oil","オリーブオイル","おりーぶおいる","Olive Oil","油脂類",
         921,0,100,0,0, ve=7.4,vk=62,
         func=[fi("quercetin","オレオカンタール・ポリフェノール","豊富",["強力抗炎症","抗酸化","心血管保護サポート"])],
         effects={"skin":{"score_contribution":0.7,"reason":"ビタミンE・ポリフェノールが肌をサポート"},
                  "immune":{"score_contribution":0.6,"reason":"抗炎症成分が免疫をサポート"},
                  "brain":{"score_contribution":0.5,"reason":"良質な脂質・ポリフェノールが脳をサポート"}},
         tips=[tip("緑黄色野菜","脂溶性ビタミンの吸収率が大幅UP","油が脂溶性ビタミンの吸収を助ける")],
         tags=["オメガ9","抗炎症","抗酸化","心血管","地中海食"]),

    food("mct_oil","MCTオイル","えむしーてぃーおいる","MCT Oil","油脂類",
         860,0,99,0,0,
         func=[fi("coq10","中鎖脂肪酸（MCT）","99g",["素早いエネルギー産生","ケトン体産生","脳エネルギーサポート"])],
         effects={"brain":{"score_contribution":0.8,"reason":"ケトン体が脳のクリーンエネルギーをサポート"},
                  "muscles":{"score_contribution":0.5,"reason":"素早いエネルギー補給が筋肉をサポート"}},
         tags=["ケトジェニック","脳エネルギー","ケトン体","スポーツ"],ref=True,src="reference"),

    food("egoma_oil","えごま油","えごまあぶら","Perilla Oil","油脂類",
         921,0,100,0,0, ve=0,
         func=[fi("dha","ALA（α-リノレン酸）","約60g",["脳機能サポート","抗炎症","心血管サポート"])],
         effects={"brain":{"score_contribution":0.9,"reason":"ALA（オメガ3前駆体）が脳をサポート"},
                  "immune":{"score_contribution":0.5,"reason":"抗炎症作用が免疫をサポート"}},
         cook=["熱に弱いため生食（サラダ・かけ油）推奨","加熱すると酸化するため非加熱で"],
         tags=["オメガ3","脳","抗炎症","非加熱推奨"]),

    food("coconut_oil","ココナッツオイル","ここなっつおいる","Coconut Oil","油脂類",
         862,0,99.1,0,0, ve=0.6,vk=0.6,
         func=[fi("coq10","中鎖脂肪酸（ラウリン酸）","約50g",["抗菌・抗ウイルスサポート","エネルギー産生","腸内環境サポート"])],
         effects={"immune":{"score_contribution":0.7,"reason":"ラウリン酸が抗菌・免疫をサポート"},
                  "brain":{"score_contribution":0.5,"reason":"中鎖脂肪酸が脳エネルギーをサポート"},
                  "gut":{"score_contribution":0.5,"reason":"抗菌作用が腸内環境をサポート"}},
         tags=["ラウリン酸","抗菌","中鎖脂肪酸","ケトジェニック"]),

    food("honey","はちみつ","はちみつ","Honey","甘味類",
         303,0.2,0,80.0,0, vb2=0.01,vc=0,fol=2,
         ca=2,mg=1,k=65,na=7,ph=4,fe=0.2,
         func=[fi("quercetin","ポリフェノール・抗菌成分","少量",["抗菌サポート","抗酸化","喉のケアサポート"])],
         effects={"immune":{"score_contribution":0.6,"reason":"ポリフェノール・抗菌成分が免疫をサポート"},
                  "gut":{"score_contribution":0.5,"reason":"プレバイオティクス効果で腸をサポートする可能性があります"},
                  "sleep":{"score_contribution":0.4,"reason":"血糖の緩やかな上昇が睡眠をサポートする可能性があります"}},
         tags=["抗菌","ポリフェノール","喉","エネルギー"]),

    food("green_tea","抹茶","まっちゃ","Matcha","し好飲料類",
         324,29.6,5.3,39.5,38.5, va=2900,ve=28.1,vb1=0.6,vb2=1.35,vc=60,fol=1200,
         ca=420,mg=230,k=2700,ph=350,fe=17.0,zn=3.3,cu=0.65,mn=23.5,
         func=[fi("catechin","カテキン（EGCG）","約300mg",["強力抗酸化","脂肪燃焼サポート","抗菌","リラックスサポート"]),
               fi("gaba","テアニン","約45mg",["集中力向上サポート","リラックス","睡眠質向上サポート"])],
         effects={"brain":{"score_contribution":0.9,"reason":"テアニン・カテキンが脳の集中力・リラックスをサポート"},
                  "immune":{"score_contribution":0.8,"reason":"カテキンが免疫・抗菌をサポート"},
                  "skin":{"score_contribution":0.7,"reason":"抗酸化カテキンが肌をサポート"},
                  "sleep":{"score_contribution":0.6,"reason":"テアニンが睡眠の質をサポートする可能性があります"}},
         tips=[tip("ビタミンC食材","カテキンの吸収が高まる可能性があります","ビタミンCがカテキンの酸化を防ぐ")],
         tags=["テアニン","カテキン","抗酸化","集中力","脳"]),

    # ── コラーゲン・美容系 ──
    food("chicken_cartilage","鶏軟骨","とりなんこつ","Chicken Cartilage","肉類",
         54,8.5,1.5,2.7,0,
         ca=100,ph=90,
         func=[fi("collagen","コラーゲン（II型）","豊富",["関節サポート","肌弾力サポート","軟骨保護"]),
               fi("glucosamine","グルコサミン","豊富",["関節の柔軟性サポート","軟骨健康サポート"])],
         effects={"skin":{"score_contribution":0.8,"reason":"コラーゲンが肌の弾力をサポート"},
                  "bones":{"score_contribution":0.7,"reason":"グルコサミン・コラーゲンが関節・軟骨をサポート"}},
         tags=["コラーゲン","グルコサミン","関節","肌","軟骨"]),

    food("pigs_foot","豚足","ぶたあし","Pig's Trotter","肉類",
         230,19.4,16.5,0,0,
         ca=48,ph=100,fe=1.5,
         func=[fi("collagen","コラーゲン","超豊富",["肌弾力サポート","関節サポート","骨強化サポート"])],
         effects={"skin":{"score_contribution":1.0,"reason":"コラーゲン超豊富で肌を最強サポート"},
                  "bones":{"score_contribution":0.7,"reason":"コラーゲンが骨・関節をサポート"}},
         tips=[tip("ビタミンC（レモンなど）","コラーゲン合成が促進される可能性があります","ビタミンCがコラーゲン生成に必要")],
         tags=["コラーゲン","肌","関節","美容"]),

    food("salmon_roe","イクラ","いくら","Salmon Roe","魚介類",
         272,32.6,15.6,0.2,0, va=330,vd=44,ve=9.1,vb1=0.42,vb2=0.44,vb6=0.31,vb12=5.9,
         ca=94,mg=95,k=210,na=910,ph=530,fe=2.0,zn=2.4,se=130,
         func=[fi("dha","DHA","約1580mg",["脳機能最強サポート","記憶力"]),
               fi("epa","EPA","約750mg",["血液サラサラ","抗炎症"]),
               fi("astaxanthin","アスタキサンチン","約0.4mg",["抗酸化","目の疲れサポート"])],
         effects={"brain":{"score_contribution":1.0,"reason":"DHA超豊富で脳を最強サポート"},
                  "eyes":{"score_contribution":0.8,"reason":"アスタキサンチン・ビタミンDが目をサポート"},
                  "immune":{"score_contribution":0.7,"reason":"ビタミンD・EPAが免疫をサポート"}},
         tags=["DHA最高量","脳","目","ビタミンD"]),

    # ── 調味料 ──
    food("apple_vinegar","りんご酢","りんごず","Apple Cider Vinegar","調味料類",
         26,0.1,0,9.3,0,
         func=[fi("lactic_acid_bacteria","酢酸・ポリフェノール","豊富",["血糖値サポート","腸内環境改善","消化促進"])],
         effects={"gut":{"score_contribution":0.7,"reason":"酢酸が腸内環境をサポート"},
                  "immune":{"score_contribution":0.4,"reason":"ポリフェノールが免疫をサポート"}},
         tags=["血糖値","腸活","消化","デトックス"]),

    food("black_sugar","黒糖","こくとう","Black Sugar","砂糖類",
         356,1.7,0.2,89.9,0, vb1=0.05,vb2=0.03,vb6=0.08,
         ca=240,mg=31,k=1100,fe=4.7,
         effects={"bones":{"score_contribution":0.5,"reason":"カルシウムが骨をサポート"}},
         tags=["カルシウム","ミネラル","鉄分","自然甘味料"]),
]

def main():
    data = {"foods": FOODS, "total": len(FOODS)}
    with open(OUT, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"✅ {len(FOODS)}食材 → {OUT}")
    # validate
    import subprocess, sys
    r = subprocess.run(['python3', '-c', f"import json; d=json.load(open('{OUT}')); print(f'検証OK: {{d[\"total\"]}}食材')"], capture_output=True, text=True)
    print(r.stdout.strip())

if __name__ == '__main__':
    main()
